Add-PsSnapIn Microsoft.SharePoint.PowerShell -ErrorAction SilentlyContinue

$siteUrl = "http://sp2013vm" #your site address here
$web = Get-SPWeb $siteUrl
$list = $web.Lists["Movies"]

function Add-NewItem($title, $description, $rating, $releaseDate, $videoUrl, $thumbnail) {
    $item = $list.Items.Add()
    $contentType = $list.ContentTypes | ?{$_.Name -eq "Item"}
    $item["ContentType"] = $contentType
	$item["Title"] = $title
	$item["Description"] = $description
	$item["Rating"] = $rating
	$item["Release Date"] = $releaseDate
	$item["Thumbnail"] = "$thumbnail, Thumbnail"
	$item["Video URL"] = "$videoUrl, Video"
    $item.Update()
}

Add-NewItem "X-Men: Days of Future Past" "The ultimate X-Men ensemble fights a war for the survival of the species across two time periods in X-MEN: DAYS OF FUTURE PAST. The beloved characters from the original X-Men film trilogy join forces with their younger selves from the past, X-Men: First Class, in order to change a major historical event and fight in an epic battle that could save our future." "M" "05-18-2014" "https://www.youtube.com/watch?v=gsjtg7m1MMM" "http://content7.flixster.com/movie/11/17/70/11177049_det.jpg"
Add-NewItem "A Million Ways to Die in the West" "Seth MacFarlane directs, produces, co-writes and plays the role of the cowardly sheep farmer Albert in A Million Ways to Die in the West. After Albert backs out of a gunfight, his fickle girlfriend leaves him for another man. When a mysterious and beautiful woman rides into town, she helps him find his courage and they begin to fall in love. But when her husband, a notorious outlaw, arrives seeking revenge, the farmer must put his newfound courage to the test. Starring alongside MacFarlane are Oscar (R) winner Charlize Theron, Liam Neeson, Amanda Seyfried, Giovanni Ribisi, Sarah Silverman and Neil Patrick Harris. MacFarlane reunites many of the filmmakers behind Universal and MRC's hit film Ted including Scott Stuber (Bluegrass Films) and Jason Clark who produce, and Wellesley Wild and Alec Sulkin who co-wrote the script​" "R16" "5-30-2014" "https://www.youtube.com/watch?v=CXxqG4aqwY4" "http://content8.flixster.com/rtmovie/11/78/117878_gal.jpg"
Add-NewItem "Rio 2" "It's a jungle out there for Blu, Jewel and their three kids in RIO 2, after they're hurtled from that magical city to the wilds of the Amazon. As Blu tries to fit in, he goes beak-to-beak with the vengeful Nigel, and meets the most fearsome adversary of all - his father-in-law. All our favorite RIO characters are back, and they're joined by Oscar (R) nominee Andy Garcia, Grammy (R) winner Bruno Mars, Tony (R) winner Kristin Chenoweth and Oscar/Emmy (R)/Tony winner Rita Moreno. RIO 2 alsofeatures new Brazilian artists and original music by Janelle Monae and Wondaland​" "G" "4-11-2014" "https://www.youtube.com/watch?v=IkZM1Zc0mBU" "http://content7.flixster.com/movie/11/17/70/11177081_det.jpg"
Add-NewItem "Bad Neighbours" "Seth Rogen, Zac Efron and Rose Byrne lead the cast of Neighbors, a comedy about a young couple suffering from arrested development who are forced to live next to a fraternity house after the birth of their newborn baby. Neighbors is directed by Nick Stoller (Forgetting Sarah Marshall, Get Him to the Greek)​" "R16" "5-09-2014" "https://www.youtube.com/watch?v=4zEUuzj3a2g" "http://content8.flixster.com/movie/11/17/55/11175594_det.jpg"
Add-NewItem "Godzilla" "In Summer 2014, the world's most revered monster is reborn as Warner Bros. Pictures and Legendary Pictures unleash the epic action adventure Godzilla. From visionary new director Gareth Edwards (Monsters) comes a powerful story of human courage and reconciliation in the face of titanic forces of nature, when the awe-inspiring Godzilla rises to restore balance as humanity stands defenseless. ​" "M" "5-16-2014" "https://www.youtube.com/watch?v=vIu85WQTPRc" "http://content7.flixster.com/movie/11/17/70/11177033_det.jpg"
Add-NewItem "The Amazing Spider-Man 2" "We've always known that Spider-Man's most important battle has been within himself: the struggle between the ordinary obligations of Peter Parker and the extraordinary responsibilities of Spider-Man. But in The Amazing Spider-Man 2, Peter Parker finds that a greater conflict lies ahead. It's great to be Spider-Man (Andrew Garfield). For Peter Parker, there's no feeling quite like swinging between skyscrapers, embracing being the hero, and spending time with Gwen (Emma Stone). But beingSpider-Man comes at a price: only Spider-Man can protect his fellow New Yorkers from the formidable villains that threaten the city. With the emergence of Electro (Jamie Foxx), Peter must confront a foe far more powerful than he. And as his old friend, Harry Osborn (Dane DeHaan), returns, Peter comes to realize that all of his enemies have one thing in common: OsCorp.​" "M" "5-2-2014" "https://www.youtube.com/watch?v=nbp3Ra3Yp74" "http://content8.flixster.com/movie/11/17/72/11177270_det.jpg"
Add-NewItem "How to Train Your Dragon 2" "DreamWorks Animation returns to the world of dragons and Vikings in this sequel to their successful 2010 outing How to Train Your Dragon. The original film followed the exploits of a Viking chief's son, who must capture a dragon in order to mark his passage into manhood and prove his worthiness to the tribe" "PG" "6-13-2014" "https://www.youtube.com/watch?v=Z9a4PvzlqoQ" "http://content7.flixster.com/movie/11/17/49/11174941_det.jpg"
Add-NewItem "22 Jump Street" "After making their way through high school (twice), big changes are in store for officers Schmidt (Jonah Hill) and Jenko (Channing Tatum) when they go deep undercover at a local college. But when Jenko meets a kindred spirit on the football team, and Schmidt infiltrates the bohemian art major scene, they begin to question their partnership. Now they don't have to just crack the case - they have to figure out if they can have a mature relationship. If these two overgrown adolescents can grow fromfreshmen into real men, college might be the best thing that ever happened to them​" "M" "6-13-2014" "https://www.youtube.com/watch?v=qP755JkDxyM" "http://content6.flixster.com/movie/11/17/61/11176100_det.jpg"
Add-NewItem "Chef" "Chef Carl Casper (Jon Favreau) suddenly quits his job at a prominent Los Angeles restaurant after refusing to compromise his creative integrity for its controlling owner (Dustin Hoffman), he is left to figure out what's next. Finding himself in Miami, he teams up with his ex-wife (Sofia Vergara), his friend (John Leguizamo) and his son to launch a food truck. Taking to the road, Chef Carl goes back to his roots to reignite his passion for the kitchen -- and zest for life and love.​" "R16" "5-9-2014" "https://www.youtube.com/watch?v=wgFws3AoIUY" "http://content9.flixster.com/movie/11/17/72/11177251_det.jpg"
Add-NewItem "The Wolf of Wall Street" "Martin Scorsese directs the story of New York stockbroker Jordan Belfort. From the American dream to corporate greed, Belfort goes from penny stocks and righteousness to IPOs and a life of corruption in the late 80s. Excess success and affluence in his early twenties as founder of the brokerage firm Stratton Oakmont warranted Belfort the title The Wolf of Wall Street.​" "R18" "12-25-2013" "https://www.youtube.com/watch?v=iszwuX1AK6A" "http://content6.flixster.com/movie/11/17/69/11176976_det.jpg"
Add-NewItem "The Hobbit: The Desolation Of Smaug" "The second in a trilogy of films adapting the enduringly popular masterpiece The Hobbit, by J.R.R. Tolkien, The Hobbit: The Desolation of Smaug continues the adventure of the title character Bilbo Baggins (Martin Freeman) as he journeys with the Wizard Gandalf (Ian McKellan) and thirteen Dwarves, led by Thorin Oakenshield (Richard Armitage) on an epic quest to reclaim the lost Dwarf Kingdom of Erebor​" "M" "12-13-2013" "https://www.youtube.com/watch?v=OPVWy1tFXuc" "http://content6.flixster.com/movie/11/17/69/11176940_det.jpg"
Add-NewItem "The Fault In Our Stars" "Hazel and Gus are two extraordinary teenagers who share an acerbic wit, a disdain for the conventional, and a love that sweeps them - and us - on an unforgettable journey. Their relationship is all the more miraculous, given that they met and fell in love at a cancer support group. THE FAULT IN OUR STARS, based upon the number-one bestselling novel by John Green, explores the funny, thrilling and tragic business of being alive and in love." "PG" "6-6-2014" "https://www.youtube.com/watch?v=9ItBvH5J6ss" "http://content6.flixster.com/movie/11/17/61/11176136_det.jpg"
Add-NewItem "Edge of Tomorrow" "The epic action of Edge of Tomorrow unfolds in a near future in which an alien race has hit the Earth in an unrelenting assault, unbeatable by any military unit in the world. Major William Cage (Tom Cruise) is an officer who has never seen a day of combat when he is unceremoniously dropped into what amounts to a suicide mission. Killed within minutes, Cage now finds himself inexplicably thrown into a time loop-forcing him to live out the same brutal combat over and over, fighting and dying again...and again. But with each battle, Cage becomes able to engage the adversaries with increasing skill, alongside Special Forces warrior Rita Vrataski (Emily Blunt). And, as Cage and Rita take the fight to the aliens, each repeated encounter gets them one step closer to defeating the enemy" "PG" "6-6-2014" "https://www.youtube.com/watch?v=yUmSVcttXnI" "http://content8.flixster.com/movie/11/17/87/11178706_det.jpg"
Add-NewItem "The LEGO Movie" "The LEGO (R) Movie is the first-ever, full-length theatrical LEGO (R) adventure. The original 3D computer animated story follows Emmet (Chris Pratt) an ordinary, rules- following, perfectly average LEGO minifigure who is mistakenly identified as the most extraordinary person and the key to saving the world. He is drafted into a fellowship of strangers on an epic quest to stop an evil tyrant, a journey for which Emmet is hopelessly and hilariously underprepared." "PG" "2-7-2014" "https://www.youtube.com/watch?v=fZ_JOBCLF-I" "http://content9.flixster.com/movie/11/17/76/11177655_det.jpg"
Add-NewItem "Lone Survivor" "LONE SURVIVOR, starring Mark Wahlberg, tells the story of four Navy SEALs on an ill-fated covert mission to neutralize a high-level Taliban operative who are ambushed by enemy forces in the Hindu Kush region of Afghanistan. Based on The New York Times bestseller, this story of heroism, courage and survival directed by Peter Berg (Friday Night Lights) also stars Taylor Kitsch, Emile Hirsch, Ben Foster and Eric Bana" "R16" "1-10-2014" "https://www.youtube.com/watch?v=yoLFk4JK_RM" "http://content6.flixster.com/movie/11/17/84/11178408_det.jpg"
Add-NewItem "Her" "Spike Jonze takes the helm for this comedy about a withdrawn writer (Joaquin Phoenix) who falls in love with his computer's highly advanced operating system." "R18" "12-18-2013" "https://www.youtube.com/watch?v=WzV6mXIOVl4" "http://content6.flixster.com/movie/11/17/76/11177656_det.jpg"
Add-NewItem "The Grand Budapest Hotel" "THE GRAND BUDAPEST HOTEL recounts the adventures of Gustave H, a legendary concierge at a famous European hotel between the wars, and Zero Moustafa, the lobby boy who becomes his most trusted friend. The story involves the theft and recovery of a priceless Renaissance painting and the battle for an enormous family fortune -- all against the back-drop ofa suddenly and dramatically changing Continent" "R16" "3-7-2014" "https://www.youtube.com/watch?v=1Fg5iWmQjwk" "http://content9.flixster.com/movie/11/17/85/11178563_det.jpg"
Add-NewItem "Philomena" "Based on the 2009 investigative book by BBC correspondent Martin Sixsmith, The Lost Child of Philomena Lee, PHILOMENA focuses on the efforts of Philomena Lee (Dench), mother to a boy conceived out of wedlock - something her Irish-Catholic community didn't have the highest opinion of - and given away for adoption in the United States. In following church doctrine, she was forced to sign a contract that wouldn't allow for any sort of inquiry into the son's whereabouts. After starting a family years later in England and, for the most part, moving on with her life, Lee meets Sixsmith (Coogan), a BBC reporter with whom she decides to discover her long-lost son" "PG" "11-22-2013" "https://www.youtube.com/watch?v=4DBPqcp6Hc4" "http://content7.flixster.com/movie/11/17/69/11176929_det.jpg"
